### ISSUE TITLE
Fix `departureTimeMinutes` for delayed services

### ISSUE THREAD

**Issue by leftshift** [leftshift/python_mvg_api#19]
It appears the planned departure time and delay are now returned separately from the API.

This leads to wrong values in `departureTimeMinutes` in the departure dicts for delayed services and very wrong values for departures with a planned departure time in the past.

**Comment by Bastlwastl42** [comment]
I observed this as well, here are some of my findings:
- i used the field _live_ before in order to indicate that informations are at least supposed to be live, however this field looks like it is false per default since beginning of december
- departures which in principle did have live time information now have a field _delay_, departures without such information don't have this field. If departures are on time, the delay is 0.
- i started to doubt the information that are provided, like as a general observation, i don't trust certain lines to be _only delayed by 2 minutes_

**Comment by leftshift** [comment]
Thanks for investigating :)

I'd be quite interested in someone comparing the values from the API with the values displayed on the screens in the stations, especially for delayed services.

As I'm currently not in Munich, it's hard for me to properly look into this myself. To me, it sounds like the best way forward is to add the `delay` to the `departureTimeMinutes` (which does not exist in the API but is generated by the library).

If anyone feels like creating a pull request for that, I'd be happy to merge it.
